### ISSUE TITLE
Copyright Notice

### ISSUE THREAD

**Issue by adamalston** [aboelkassem/LandingPage#1]
Hi, 
If you are going to use my website without attribution, I ask that you comply with the following:
1. Remove the favicon from the site itself and the README as it is subject to copyright.
2. Alter the design of the site from its current state; If the site is `Designed and built by aboelkassem,` the appearance of the site should reflect that.

However, all of these things can remain if you abide by the implicit agreement set forth under the [Open Source](https://github.com/adamalston/v2#-open-source) section of my project including, but not limited to, correct attribution.

I worked hard to design this website. My work is not gratuitous unless attribution is correctly applied.

**Comment by mkassm** [comment]
Hello Adam,
Thank you for notifying me about this copyright issue.

I'm really sorry for that but I don't notice this problem, I just use Find and Replace keywords in vs code in all documents to get my stuff. because you doing great work on this website and made it open source.

I had made the changes you asked for that make the sign back to you, you can check it.
